CREATE TABLE IF NOT EXISTS Services {
    id INT NOT NULL AUTO_INCREMENT,
	ServicesType INT NOT NULL,
	ServiceName INT NOT NULL,
	QTY INT NOT NULL,
	
	PRIMARY KEY (id)
	}

CREATE TABLE IF NOT EXISTS ResServices {
	id INT NOT NULL AUTO_INCREMENT,
	ServiceID INT NOT NULL,
	WalkInID INT NOT NULL,
	ResDate DATE NOT NULL,
	
	PRIMARY KEY (id),
	FOREIGN KEY (ServiceID) REFERENCES Services(id)
}
	
